name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'  # Cache Yarn dependencies
    - run: yarn install --frozen-lockfile  # Use Yarn to install dependencies
    - run: yarn build --if-present  # Build the project with Yarn
    - run: yarn test  # Run tests with Yarn
